FROM ubuntu:20.04

ARG PROFILE=release
ARG BINARY=interbtc-parachain

# install tools and dependencies
RUN apt-get update && \
       DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
       DEBIAN_FRONTEND=noninteractive apt-get install -y \
               libssl1.1 \
               ca-certificates \
               curl && \
# apt cleanup
       apt-get autoremove -y && \
       apt-get clean && \
       find /var/lib/apt/lists/ -type f -not -name lock -delete

COPY target/${PROFILE}/${BINARY} /usr/local/bin

# Checks
RUN chmod +x /usr/local/bin/${BINARY} && \
    ldd /usr/local/bin/${BINARY} && \
    /usr/local/bin/${BINARY} --version

EXPOSE 30333 9933 9944
VOLUME ["/data"]

ENTRYPOINT ["/usr/local/bin/${BINARY}"]
