FROM ubuntu:20.04

ARG PROFILE=release
ARG BINARY=interbtc-parachain

ENV DEBIAN_FRONTEND=noninteractive

# install tools and dependencies
RUN apt-get update && apt-get upgrade -y && \
      apt-get install -y libssl1.1 ca-certificates curl && \
      apt-get autoremove -y &&  apt-get clean && \
      find /var/lib/apt/lists/ -type f -not -name lock -delete

COPY target/${PROFILE}/interbtc-parachain /usr/local/bin

# Checks
RUN chmod +x /usr/local/bin/interbtc-parachain && \
    ldd /usr/local/bin/interbtc-parachain && \
    /usr/local/bin/interbtc-parachain --version

EXPOSE 30333 9933 9944
VOLUME ["/data"]

ENTRYPOINT ["/usr/local/bin/interbtc-parachain"]
