
//! Autogenerated weights for loans
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-03-31, STEPS: `100`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `interlay-hetzner-01`, CPU: `AMD EPYC 7502P 32-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("kintsugi-testnet-latest"), DB CACHE: 1024

// Executed Command:
// target/release/interbtc-parachain
// benchmark
// pallet
// --chain
// kintsugi-testnet-latest
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// loans
// --extrinsic
// *
// --steps
// 100
// --repeat
// 10
// --output
// ./crates/loans/src/default_weights.rs
// --template
// .deploy/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for loans.
pub trait WeightInfo {
	fn add_market() -> Weight;
	fn activate_market() -> Weight;
	fn update_rate_model() -> Weight;
	fn update_market() -> Weight;
	fn force_update_market() -> Weight;
	fn add_reward() -> Weight;
	fn update_market_reward_speed() -> Weight;
	fn claim_reward() -> Weight;
	fn claim_reward_for_market() -> Weight;
	fn mint() -> Weight;
	fn borrow() -> Weight;
	fn redeem() -> Weight;
	fn redeem_all() -> Weight;
	fn repay_borrow() -> Weight;
	fn repay_borrow_all() -> Weight;
	fn deposit_all_collateral() -> Weight;
	fn withdraw_all_collateral() -> Weight;
	fn add_reserves() -> Weight;
	fn reduce_reserves() -> Weight;
}

/// Weights for loans using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Loans Markets (r:2 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:1)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans ExchangeRate (r:0 w:1)
	/// Proof Skipped: Loans ExchangeRate (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:0 w:1)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	fn add_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1207`
		//  Estimated: `13955`
		// Minimum execution time: 61_463_000 picoseconds.
		Weight::from_parts(62_425_000, 13955)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn activate_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1504`
		//  Estimated: `3979`
		// Minimum execution time: 37_305_000 picoseconds.
		Weight::from_parts(38_026_000, 3979)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn update_rate_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1504`
		//  Estimated: `3979`
		// Minimum execution time: 38_687_000 picoseconds.
		Weight::from_parts(39_388_000, 3979)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn update_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1504`
		//  Estimated: `3979`
		// Minimum execution time: 41_664_000 picoseconds.
		Weight::from_parts(42_365_000, 3979)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Loans UnderlyingAssetId (r:1 w:1)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn force_update_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515`
		//  Estimated: `7980`
		// Minimum execution time: 48_437_000 picoseconds.
		Weight::from_parts(49_549_000, 7980)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn add_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2308`
		//  Estimated: `7783`
		// Minimum execution time: 91_283_000 picoseconds.
		Weight::from_parts(92_344_000, 7783)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	fn update_market_reward_speed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1518`
		//  Estimated: `22440`
		// Minimum execution time: 69_760_000 picoseconds.
		Weight::from_parts(70_641_000, 22440)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:0)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3492`
		//  Estimated: `80995`
		// Minimum execution time: 205_170_000 picoseconds.
		Weight::from_parts(205_862_000, 80995)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans Markets (r:1 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:0)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward_for_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3492`
		//  Estimated: `78520`
		// Minimum execution time: 193_126_000 picoseconds.
		Weight::from_parts(193_758_000, 78520)
			.saturating_add(T::DbWeight::get().reads(16_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2944`
		//  Estimated: `73490`
		// Minimum execution time: 266_703_000 picoseconds.
		Weight::from_parts(268_177_000, 73490)
			.saturating_add(T::DbWeight::get().reads(18_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalBorrows (r:1 w:1)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:1)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	fn borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3312`
		//  Estimated: `90329`
		// Minimum execution time: 255_020_000 picoseconds.
		Weight::from_parts(256_613_000, 90329)
			.saturating_add(T::DbWeight::get().reads(20_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	fn redeem() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3368`
		//  Estimated: `82017`
		// Minimum execution time: 315_170_000 picoseconds.
		Weight::from_parts(317_545_000, 82017)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	fn redeem_all() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3368`
		//  Estimated: `82017`
		// Minimum execution time: 319_229_000 picoseconds.
		Weight::from_parts(319_840_000, 82017)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:1)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:1)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	fn repay_borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3407`
		//  Estimated: `61096`
		// Minimum execution time: 175_371_000 picoseconds.
		Weight::from_parts(176_143_000, 61096)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:1)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:1)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	fn repay_borrow_all() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3407`
		//  Estimated: `61096`
		// Minimum execution time: 193_137_000 picoseconds.
		Weight::from_parts(195_030_000, 61096)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:1)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	fn deposit_all_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2295`
		//  Estimated: `19375`
		// Minimum execution time: 99_589_000 picoseconds.
		Weight::from_parts(100_692_000, 19375)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:1)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:2 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:0)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	fn withdraw_all_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3242`
		//  Estimated: `60764`
		// Minimum execution time: 221_343_000 picoseconds.
		Weight::from_parts(222_806_000, 60764)
			.saturating_add(T::DbWeight::get().reads(15_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalReserves (r:1 w:1)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	fn add_reserves() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2768`
		//  Estimated: `26490`
		// Minimum execution time: 127_716_000 picoseconds.
		Weight::from_parts(128_938_000, 26490)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:1)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn reduce_reserves() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2857`
		//  Estimated: `26757`
		// Minimum execution time: 112_235_000 picoseconds.
		Weight::from_parts(112_916_000, 26757)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Loans Markets (r:2 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:1)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans ExchangeRate (r:0 w:1)
	/// Proof Skipped: Loans ExchangeRate (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:0 w:1)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	fn add_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1207`
		//  Estimated: `13955`
		// Minimum execution time: 61_463_000 picoseconds.
		Weight::from_parts(62_425_000, 13955)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn activate_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1504`
		//  Estimated: `3979`
		// Minimum execution time: 37_305_000 picoseconds.
		Weight::from_parts(38_026_000, 3979)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn update_rate_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1504`
		//  Estimated: `3979`
		// Minimum execution time: 38_687_000 picoseconds.
		Weight::from_parts(39_388_000, 3979)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn update_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1504`
		//  Estimated: `3979`
		// Minimum execution time: 41_664_000 picoseconds.
		Weight::from_parts(42_365_000, 3979)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Loans UnderlyingAssetId (r:1 w:1)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans Markets (r:1 w:1)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	fn force_update_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515`
		//  Estimated: `7980`
		// Minimum execution time: 48_437_000 picoseconds.
		Weight::from_parts(49_549_000, 7980)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn add_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2308`
		//  Estimated: `7783`
		// Minimum execution time: 91_283_000 picoseconds.
		Weight::from_parts(92_344_000, 7783)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	fn update_market_reward_speed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1518`
		//  Estimated: `22440`
		// Minimum execution time: 69_760_000 picoseconds.
		Weight::from_parts(70_641_000, 22440)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:0)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3492`
		//  Estimated: `80995`
		// Minimum execution time: 205_170_000 picoseconds.
		Weight::from_parts(205_862_000, 80995)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans Markets (r:1 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:0)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward_for_market() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3492`
		//  Estimated: `78520`
		// Minimum execution time: 193_126_000 picoseconds.
		Weight::from_parts(193_758_000, 78520)
			.saturating_add(RocksDbWeight::get().reads(16_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2944`
		//  Estimated: `73490`
		// Minimum execution time: 266_703_000 picoseconds.
		Weight::from_parts(268_177_000, 73490)
			.saturating_add(RocksDbWeight::get().reads(18_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalBorrows (r:1 w:1)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:1)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	fn borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3312`
		//  Estimated: `90329`
		// Minimum execution time: 255_020_000 picoseconds.
		Weight::from_parts(256_613_000, 90329)
			.saturating_add(RocksDbWeight::get().reads(20_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	fn redeem() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3368`
		//  Estimated: `82017`
		// Minimum execution time: 315_170_000 picoseconds.
		Weight::from_parts(317_545_000, 82017)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:3 w:3)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:0)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplyState (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplyState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplySpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardSupplySpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardSupplierIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardSupplierIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	fn redeem_all() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3368`
		//  Estimated: `82017`
		// Minimum execution time: 319_229_000 picoseconds.
		Weight::from_parts(319_840_000, 82017)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:1)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:1)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	fn repay_borrow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3407`
		//  Estimated: `61096`
		// Minimum execution time: 175_371_000 picoseconds.
		Weight::from_parts(176_143_000, 61096)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:1)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans BorrowIndex (r:1 w:0)
	/// Proof Skipped: Loans BorrowIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowState (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowState (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowSpeed (r:1 w:0)
	/// Proof Skipped: Loans RewardBorrowSpeed (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardBorrowerIndex (r:1 w:1)
	/// Proof Skipped: Loans RewardBorrowerIndex (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans RewardAccrued (r:1 w:1)
	/// Proof Skipped: Loans RewardAccrued (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:1)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	fn repay_borrow_all() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3407`
		//  Estimated: `61096`
		// Minimum execution time: 193_137_000 picoseconds.
		Weight::from_parts(195_030_000, 61096)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:1)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	fn deposit_all_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2295`
		//  Estimated: `19375`
		// Minimum execution time: 99_589_000 picoseconds.
		Weight::from_parts(100_692_000, 19375)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans AccountDeposits (r:1 w:1)
	/// Proof Skipped: Loans AccountDeposits (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans UnderlyingAssetId (r:1 w:0)
	/// Proof Skipped: Loans UnderlyingAssetId (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens TotalIssuance (r:1 w:0)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(35), added: 2510, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:2 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalBorrows (r:1 w:0)
	/// Proof Skipped: Loans TotalBorrows (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:0)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans MinExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MinExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans MaxExchangeRate (r:1 w:0)
	/// Proof Skipped: Loans MaxExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Loans AccountBorrows (r:1 w:0)
	/// Proof Skipped: Loans AccountBorrows (max_values: None, max_size: None, mode: Measured)
	fn withdraw_all_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3242`
		//  Estimated: `60764`
		// Minimum execution time: 221_343_000 picoseconds.
		Weight::from_parts(222_806_000, 60764)
			.saturating_add(RocksDbWeight::get().reads(15_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Loans TotalReserves (r:1 w:1)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	fn add_reserves() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2768`
		//  Estimated: `26490`
		// Minimum execution time: 127_716_000 picoseconds.
		Weight::from_parts(128_938_000, 26490)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Loans Markets (r:2 w:0)
	/// Proof Skipped: Loans Markets (max_values: None, max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Loans LastAccruedInterestTime (r:1 w:1)
	/// Proof Skipped: Loans LastAccruedInterestTime (max_values: None, max_size: None, mode: Measured)
	/// Storage: Loans TotalReserves (r:1 w:1)
	/// Proof Skipped: Loans TotalReserves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Tokens Accounts (r:2 w:2)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(115), added: 2590, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn reduce_reserves() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2857`
		//  Estimated: `26757`
		// Minimum execution time: 112_235_000 picoseconds.
		Weight::from_parts(112_916_000, 26757)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
