
//! Autogenerated weights for clients_info
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-08, STEPS: `50`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `interlay-hetzner-01`, CPU: `AMD EPYC 7502P 32-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("interlay-dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/interbtc-parachain
// benchmark
// pallet
// --pallet
// *
// --extrinsic
// *
// --chain
// interlay-dev
// --execution=wasm
// --wasm-execution=compiled
// --steps
// 50
// --repeat
// 10
// --output
// parachain/runtime/interlay/src/weights/
// --template
// .deploy/runtime-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for clients_info using the Substrate node and recommended hardware.
pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> clients_info::WeightInfo for WeightInfo<T> {

	/// Storage: ClientsInfo CurrentClientReleases (r:0 w:1)
	/// Proof: ClientsInfo CurrentClientReleases (max_values: None, max_size: Some(562), added: 3037, mode: MaxEncodedLen)
	/// The range of component `n` is `[0, 255]`.
	/// The range of component `u` is `[0, 255]`.
	fn set_current_client_release	(n: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_606_000 picoseconds.
		Weight::from_parts(23_214_319, 0)
			// Standard Error: 355
			.saturating_add(Weight::from_parts(2_953, 0).saturating_mul(n.into()))
			// Standard Error: 355
			.saturating_add(Weight::from_parts(1_249, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: ClientsInfo PendingClientReleases (r:0 w:1)
	/// Proof: ClientsInfo PendingClientReleases (max_values: None, max_size: Some(562), added: 3037, mode: MaxEncodedLen)
	/// The range of component `n` is `[0, 255]`.
	/// The range of component `u` is `[0, 255]`.
	fn set_pending_client_release	(n: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 22_495_000 picoseconds.
		Weight::from_parts(23_222_048, 0)
			// Standard Error: 529
			.saturating_add(Weight::from_parts(2_781, 0).saturating_mul(n.into()))
			// Standard Error: 529
			.saturating_add(Weight::from_parts(1_888, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}