
//! Autogenerated weights for democracy
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-14, STEPS: `100`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `enterprise`, CPU: `Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("kintsugi-dev"), DB CACHE: 1024

// Executed Command:
// target/release/interbtc-parachain
// benchmark
// pallet
// --pallet
// democracy
// --extrinsic
// *
// --chain
// kintsugi-dev
// --execution=wasm
// --wasm-execution=compiled
// --steps
// 100
// --repeat
// 10
// --output
// crates/democracy/src/default_weights.rs
// --template
// .deploy/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for democracy.
pub trait WeightInfo {
	fn propose() -> Weight;
	fn second() -> Weight;
	fn vote_new() -> Weight;
	fn vote_existing() -> Weight;
	fn fast_track() -> Weight;
	fn fast_track_referendum() -> Weight;
	fn cancel_proposal() -> Weight;
	fn cancel_referendum() -> Weight;
	fn on_initialize_public(r: u32, ) -> Weight;
	fn on_initialize_base(r: u32, ) -> Weight;
	fn on_initialize_base_with_launch_period(r: u32, ) -> Weight;
	fn clear_public_proposals() -> Weight;
	fn remove_vote(r: u32, ) -> Weight;
}

/// Weights for democracy using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Democracy PublicPropCount (r:1 w:1)
	/// Proof Skipped: Democracy PublicPropCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:0 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	fn propose() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7370`
		//  Estimated: `52635`
		// Minimum execution time: 62_061_000 picoseconds.
		Weight::from_parts(63_277_000, 52635)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	fn second() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6034`
		//  Estimated: `34036`
		// Minimum execution time: 52_327_000 picoseconds.
		Weight::from_parts(53_272_000, 34036)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:0)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy VotingOf (r:1 w:1)
	/// Proof Skipped: Democracy VotingOf (max_values: None, max_size: None, mode: Measured)
	fn vote_new() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4422`
		//  Estimated: `34485`
		// Minimum execution time: 51_494_000 picoseconds.
		Weight::from_parts(52_935_000, 34485)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:0)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy VotingOf (r:1 w:1)
	/// Proof Skipped: Democracy VotingOf (max_values: None, max_size: None, mode: Measured)
	fn vote_existing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4443`
		//  Estimated: `34590`
		// Minimum execution time: 52_182_000 picoseconds.
		Weight::from_parts(53_614_000, 34590)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:0 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	fn fast_track() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1658`
		//  Estimated: `14230`
		// Minimum execution time: 53_171_000 picoseconds.
		Weight::from_parts(53_891_000, 14230)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	fn fast_track_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1274`
		//  Estimated: `3749`
		// Minimum execution time: 32_876_000 picoseconds.
		Weight::from_parts(33_975_000, 3749)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	fn cancel_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7118`
		//  Estimated: `26799`
		// Minimum execution time: 61_323_000 picoseconds.
		Weight::from_parts(62_727_000, 26799)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	fn cancel_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1274`
		//  Estimated: `3749`
		// Minimum execution time: 30_016_000 picoseconds.
		Weight::from_parts(30_868_000, 3749)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Democracy LowestUnbaked (r:1 w:0)
	/// Proof Skipped: Democracy LowestUnbaked (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Democracy NextLaunchTimestamp (r:1 w:1)
	/// Proof Skipped: Democracy NextLaunchTimestamp (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:99 w:100)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Epoch (r:1 w:0)
	/// Proof Skipped: Escrow Epoch (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Escrow PointHistory (r:1 w:0)
	/// Proof Skipped: Escrow PointHistory (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 99]`.
	fn on_initialize_public(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1476 + r * (117 ±0)`
		//  Estimated: `23689 + r * (3537 ±0)`
		// Minimum execution time: 55_875_000 picoseconds.
		Weight::from_parts(60_503_027, 23689)
			// Standard Error: 15_500
			.saturating_add(Weight::from_parts(10_761_596, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 3537).saturating_mul(r.into()))
	}
	/// Storage: Democracy LowestUnbaked (r:1 w:0)
	/// Proof Skipped: Democracy LowestUnbaked (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:0)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Democracy NextLaunchTimestamp (r:1 w:1)
	/// Proof Skipped: Democracy NextLaunchTimestamp (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:0)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:99 w:0)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 99]`.
	fn on_initialize_base(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `644 + r * (117 ±0)`
		//  Estimated: `5704 + r * (3065 ±0)`
		// Minimum execution time: 14_067_000 picoseconds.
		Weight::from_parts(31_791_294, 5704)
			// Standard Error: 20_403
			.saturating_add(Weight::from_parts(3_080_890, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 3065).saturating_mul(r.into()))
	}
	/// Storage: Democracy LowestUnbaked (r:1 w:0)
	/// Proof Skipped: Democracy LowestUnbaked (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:0)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Democracy NextLaunchTimestamp (r:1 w:1)
	/// Proof Skipped: Democracy NextLaunchTimestamp (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:0)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:99 w:0)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 99]`.
	fn on_initialize_base_with_launch_period(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `644 + r * (117 ±0)`
		//  Estimated: `5704 + r * (3065 ±0)`
		// Minimum execution time: 13_856_000 picoseconds.
		Weight::from_parts(24_677_720, 5704)
			// Standard Error: 15_211
			.saturating_add(Weight::from_parts(3_224_809, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 3065).saturating_mul(r.into()))
	}
	/// Storage: Democracy PublicProps (r:0 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	fn clear_public_proposals() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `711`
		//  Estimated: `711`
		// Minimum execution time: 8_905_000 picoseconds.
		Weight::from_parts(9_172_000, 711)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy VotingOf (r:1 w:1)
	/// Proof Skipped: Democracy VotingOf (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[1, 100]`.
	fn remove_vote(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1371 + r * (25 ±0)`
		//  Estimated: `7614 + r * (52 ±0)`
		// Minimum execution time: 25_331_000 picoseconds.
		Weight::from_parts(29_925_302, 7614)
			// Standard Error: 5_168
			.saturating_add(Weight::from_parts(52_885, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 52).saturating_mul(r.into()))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Democracy PublicPropCount (r:1 w:1)
	/// Proof Skipped: Democracy PublicPropCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:0 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	fn propose() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7370`
		//  Estimated: `52635`
		// Minimum execution time: 62_061_000 picoseconds.
		Weight::from_parts(63_277_000, 52635)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	fn second() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6034`
		//  Estimated: `34036`
		// Minimum execution time: 52_327_000 picoseconds.
		Weight::from_parts(53_272_000, 34036)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:0)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy VotingOf (r:1 w:1)
	/// Proof Skipped: Democracy VotingOf (max_values: None, max_size: None, mode: Measured)
	fn vote_new() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4422`
		//  Estimated: `34485`
		// Minimum execution time: 51_494_000 picoseconds.
		Weight::from_parts(52_935_000, 34485)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointEpoch (r:1 w:0)
	/// Proof Skipped: Escrow UserPointEpoch (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow UserPointHistory (r:1 w:0)
	/// Proof Skipped: Escrow UserPointHistory (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:0)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy VotingOf (r:1 w:1)
	/// Proof Skipped: Democracy VotingOf (max_values: None, max_size: None, mode: Measured)
	fn vote_existing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4443`
		//  Estimated: `34590`
		// Minimum execution time: 52_182_000 picoseconds.
		Weight::from_parts(53_614_000, 34590)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:0 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	fn fast_track() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1658`
		//  Estimated: `14230`
		// Minimum execution time: 53_171_000 picoseconds.
		Weight::from_parts(53_891_000, 14230)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	fn fast_track_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1274`
		//  Estimated: `3749`
		// Minimum execution time: 32_876_000 picoseconds.
		Weight::from_parts(33_975_000, 3749)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	fn cancel_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7118`
		//  Estimated: `26799`
		// Minimum execution time: 61_323_000 picoseconds.
		Weight::from_parts(62_727_000, 26799)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	fn cancel_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1274`
		//  Estimated: `3749`
		// Minimum execution time: 30_016_000 picoseconds.
		Weight::from_parts(30_868_000, 3749)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Democracy LowestUnbaked (r:1 w:0)
	/// Proof Skipped: Democracy LowestUnbaked (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Democracy NextLaunchTimestamp (r:1 w:1)
	/// Proof Skipped: Democracy NextLaunchTimestamp (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy DepositOf (r:1 w:1)
	/// Proof Skipped: Democracy DepositOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Reserved (r:1 w:1)
	/// Proof Skipped: Escrow Reserved (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:99 w:100)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Escrow Epoch (r:1 w:0)
	/// Proof Skipped: Escrow Epoch (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Escrow PointHistory (r:1 w:0)
	/// Proof Skipped: Escrow PointHistory (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 99]`.
	fn on_initialize_public(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1476 + r * (117 ±0)`
		//  Estimated: `23689 + r * (3537 ±0)`
		// Minimum execution time: 55_875_000 picoseconds.
		Weight::from_parts(60_503_027, 23689)
			// Standard Error: 15_500
			.saturating_add(Weight::from_parts(10_761_596, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 3537).saturating_mul(r.into()))
	}
	/// Storage: Democracy LowestUnbaked (r:1 w:0)
	/// Proof Skipped: Democracy LowestUnbaked (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:0)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Democracy NextLaunchTimestamp (r:1 w:1)
	/// Proof Skipped: Democracy NextLaunchTimestamp (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:0)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:99 w:0)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 99]`.
	fn on_initialize_base(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `644 + r * (117 ±0)`
		//  Estimated: `5704 + r * (3065 ±0)`
		// Minimum execution time: 14_067_000 picoseconds.
		Weight::from_parts(31_791_294, 5704)
			// Standard Error: 20_403
			.saturating_add(Weight::from_parts(3_080_890, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 3065).saturating_mul(r.into()))
	}
	/// Storage: Democracy LowestUnbaked (r:1 w:0)
	/// Proof Skipped: Democracy LowestUnbaked (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumCount (r:1 w:0)
	/// Proof Skipped: Democracy ReferendumCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Democracy NextLaunchTimestamp (r:1 w:1)
	/// Proof Skipped: Democracy NextLaunchTimestamp (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy PublicProps (r:1 w:0)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Democracy ReferendumInfoOf (r:99 w:0)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 99]`.
	fn on_initialize_base_with_launch_period(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `644 + r * (117 ±0)`
		//  Estimated: `5704 + r * (3065 ±0)`
		// Minimum execution time: 13_856_000 picoseconds.
		Weight::from_parts(24_677_720, 5704)
			// Standard Error: 15_211
			.saturating_add(Weight::from_parts(3_224_809, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 3065).saturating_mul(r.into()))
	}
	/// Storage: Democracy PublicProps (r:0 w:1)
	/// Proof Skipped: Democracy PublicProps (max_values: Some(1), max_size: None, mode: Measured)
	fn clear_public_proposals() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `711`
		//  Estimated: `711`
		// Minimum execution time: 8_905_000 picoseconds.
		Weight::from_parts(9_172_000, 711)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Democracy ReferendumInfoOf (r:1 w:1)
	/// Proof Skipped: Democracy ReferendumInfoOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Democracy VotingOf (r:1 w:1)
	/// Proof Skipped: Democracy VotingOf (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[1, 100]`.
	fn remove_vote(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1371 + r * (25 ±0)`
		//  Estimated: `7614 + r * (52 ±0)`
		// Minimum execution time: 25_331_000 picoseconds.
		Weight::from_parts(29_925_302, 7614)
			// Standard Error: 5_168
			.saturating_add(Weight::from_parts(52_885, 0).saturating_mul(r.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 52).saturating_mul(r.into()))
	}
}
